source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'OpenKuiklyIOSRender' , '~> 2.16.0'
  pod 'shared', :path => '../shared'
  pod 'KuiklyDeviceCalendar', :path => '../'

  pod 'SDWebImage'
end